sudo: false
language: node_js
dist: trusty
node_js:
 - “10”

cache:
 directories:
 - “$HOME/.npm”

branches:
 only:
 - master

before_install:
- sudo apt-get update
- npm --version

install:
- npm install
- echo “npm test temporarily disabled”

script: ‘true’

after_success:
- echo “Oh hey! This build works!”
